version: "3"

services:
  client:
    image: be-project-client:latest
    ports:
      - 12000:12000
    environment:
      - HOST

  router:
    image: be-project:latest
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      AUTH: auth

  auth:
    image: be-project-authentication:latest
    ports:
      - 4242:4242
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
